Repository openshift/dpu-network-operator, pull requests merged in 2022-03, with the labels that each got.

#21 Bug 2059490: Correct ART image replacement in operator bundle
  bundle/manifests/dpu-network-operator.clusterserviceversion.yaml
  config/manifests/bases/dpu-network-operator.clusterserviceversion.yaml
  manifests/stable/dpu-network-operator.clusterserviceversion.yaml
  manifests/stable/image-references
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#23 Add arm64 label
  bundle/manifests/dpu-network-operator.clusterserviceversion.yaml
  config/manifests/bases/dpu-network-operator.clusterserviceversion.yaml
  manifests/stable/dpu-network-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#22 Bug 2059577: Correct ART image replacement in operator bundle
  Dockerfile
  Dockerfile.rhel7
  bundle/manifests/dpu-network-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/bases/dpu-network-operator.clusterserviceversion.yaml
  manifests/stable/dpu-network-operator.clusterserviceversion.yaml
  manifests/stable/image-references
Labels: staff-eng-approved, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#25 Update the CSV file to match the replacement rule in art.yaml
  bundle/manifests/dpu-network-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  manifests/stable/dpu-network-operator.clusterserviceversion.yaml
Labels: approved, lgtm
