Repository openshift/dpu-network-operator, pull requests merged in 2023-06, with the labels that each got.

#69 Delete blocking deployment if tenant node doesn't exist anymore
  controllers/dpu_node_controller.go
  pkg/utils/utils.go
Labels: approved, lgtm

#74 OCPBUGS-14179: Remove dependency to sriov_config.json configuration file
  bindata/machine-config/files/82-net-setup-link.rules.yaml
  bindata/machine-config/files/common-dpu.sh.yaml
  bindata/machine-config/files/configure-switchdev.sh.yaml
  bindata/machine-config/files/ovs-add-pf.sh.yaml
  bindata/machine-config/files/ovs-reconfig.sh.yaml
  bindata/machine-config/files/sriov_config.json.yaml
  bindata/machine-config/files/vf-net-link-name.sh.yaml
  bindata/machine-config/ovs-units/ovs-configuration.service.yaml
  controllers/ovnkubeconfig_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#75 Remove MGMT_IFNAME since it is autodetermined by node anotations in OVN-K
  README.md
  bindata/ovnkube-node/daemonset.yaml
  config-sample/env_overrides.yaml
Labels: approved, lgtm

#73 OCPBUGS-14099: Update default installation namespace
  bundle/manifests/dpu-network-operator.clusterserviceversion.yaml
  config/manifests/bases/dpu-network-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, qe-approved, jira/valid-bug, jira/valid-reference

#77 update OWNERS
  OWNERS
Labels: approved, lgtm
